# server配置
server:
  port: 8888
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
  url:
    referer:
      check: true
      pre: http://127.0.0.1:8888/
      excu: /,/page/auth/

logging:
  config: classpath:log/logback-spring.xml
  path: /logs/com.airusheng.tech/wechat-admin-platform
  
page:
  host: /view

jasypt:
  encryptor:
    password: com.airusheng
    
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  datasource: # 数据库链接信息
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: ENC(LsMQm7v3CEDQduQub5FL0d+hDBk0eEdj+wgGwOBN1eF8dOX/K8Jjb+kXHEoSYA4XfT8GoirwSy9x5TlS1oqLajkbkYk212nXlCbkskeQSFE=)
    username: ENC(FtQr4TavOU+QoEEhxDPm1JYcyvEBJHoj)
    password: ENC(KFkgLHnii3rCcqRHO3D3H5H6JjnQHkXI)
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
  redis:
    host: ENC(VB9TUv1CIJd2YgrDTKcpCWweotBwX3jh) # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    database: 1 # Redis数据库索引（默认为0）
    jedis:
      pool:
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 1 # 连接池中的最小空闲连接
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 5000 # 连接超时时间（毫秒）

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count\=countSql